fos_user:
  db_driver: mongodb # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Document\User
  from_email:
    address: '%env(MAILER_URL)%'
    sender_name: '%env(MAILER_USER)%'